Switch from request to fetch + bug fix
peerigon/scrapegoat pull request #47
Opened 2021-05-11 06:29 UTC by antosan

Fixes #37 

- Switches from request to fetch
- Updates the docs for the public API, the `sendImmediately` option is no longer supported.
- Fixes a bug with iCloud calendar where the response contains the URL to the calendar when fetching eTags and this breaks the parser.

2021-05-11 06:52 UTC, jhnns requested changes

2021-05-11 08:03 UTC, antosan commented on lib/request.js
> +            if (!res.ok || res.status >= 300) {
Done.

2021-05-14 08:07 UTC, jhnns approved these changes
Awesome 🎉

2021-05-14 08:08 UTC, merged

2021-05-14 08:11 UTC, jhnns commented
🚀 Published as 2.0.0